<a href="https://colab.research.google.com/github/madhurjyaborkotoky/deeplearning_campusx/blob/main/pytorch/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Importing torch and checking whether GPU is avaiable or not.**


In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

If we create a tensor using the empty() function, it will create a tensor with
uninitialized values, as they will create tensors with known values. Here the values are random and they are some gerbage values from the memory. So, we should not use the empty() function to create a tensor if we want to have known values. Instead we can use the ones() or zeros() function to create a tensor with known values. The ones() function will create a tensor with all values as 1 and the zeros() function will create a tensor with all values as 0. The rand() function will create a tensor with random values between 0 and 1. The rand() function will create a tensor with random values hence if we run the code multiple times, we will get different values each time.

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.5103, 0.4797, 0.8645],
        [0.7043, 0.5100, 0.9206]])

In [ ]:
# use of seed
torch.rand(2,3)

tensor([[0.9448, 0.8088, 0.9701],
        [0.7353, 0.8110, 0.7792]])

We run the code torch.rand() two times and we got different values each time. This is because the rand() function generates random values between 0 and 1. If we want to have the same random values each time we run the code, we can set the seed the same value using the torch.manual_seed() function.

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

We can choose the seed value any integer as we want. This seed is used to generate a sequence of random number.

# **`torch.manual_seed()` — Understanding the Seed**

`torch.manual_seed(seed)` is used to initialize PyTorch's **pseudo-random number generator (PRNG)** with a specified seed.

## **What is a Seed?**

A computer does not normally generate truly random numbers using ordinary deterministic algorithms. Instead, PyTorch uses a **pseudo-random number generator**, which produces numbers that appear random but are generated through a deterministic process.

The seed is used to determine the **initial state** of the random number generator.

The important point is that the seed is **not itself a random number** that PyTorch returns. For example, using a seed of 42 does not mean that PyTorch will generate the number 42.

Conceptually:

**Seed → Initial RNG State → PRNG Algorithm → Random-looking Sequence**

Once the initial state is fixed, the generator can produce a deterministic sequence of values.

## **Why is an Integer Passed to `manual_seed()`?**

A pseudo-random number generator needs an initial state from which it can begin producing its sequence.

The integer passed to `manual_seed()` provides the information needed to initialize that state.

Conceptually:

**Seed → Initial RNG State → Random Number → Updated RNG State → Next Random Number → ...**

After generating a random value, the internal state of the generator changes. The next random value is therefore different, but it is still determined by the previous state and the underlying algorithm.

Thus, the seed essentially determines the **starting point of a deterministic pseudo-random sequence**.

## **Why Does the Same Seed Produce the Same Results?**

Suppose the generator starts with the same seed and performs exactly the same sequence of random operations. Since the underlying PRNG algorithm is deterministic, the generator follows the same sequence of internal states and produces the same sequence of random values.

Therefore:

**Same seed + same RNG algorithm + same sequence of operations → same pseudo-random sequence**

This is the basis of **reproducibility** in machine-learning experiments.

## **Why is This Important in Neural Networks?**

Neural-network training involves randomness in several places, including:

* Random initialization of model weights
* Shuffling of training data
* Dropout
* Random data augmentation
* Other stochastic operations

Consequently, two runs of the same neural-network program can produce different results if their random-number sequences are different.

Setting a fixed seed allows the random operations to start from a known state. Under the same relevant conditions, this makes it possible to reproduce the same sequence of random operations and therefore obtain reproducible experiments.

Conceptually:

**Seed → Random Values → Initial Weights / Other Random Operations → Training → Final Model**

This is why a fixed seed is commonly used during experimentation.

## **Is `100` a Special Seed?**

No. There is **nothing mathematically special about the value 100**.

Values such as 0, 1, 42, 123, or 2026 can all be used as seeds. The purpose of choosing a particular value is simply to establish a known starting state.

Therefore, the seed is generally **not a hyperparameter that needs to be optimized**. It is primarily a tool for controlling randomness and improving reproducibility.

## **What is the Range of the Seed?**

According to PyTorch's documentation, `torch.manual_seed()` accepts an integer in the inclusive range

[
-2^{63} \leq \text{seed} \leq 2^{64}-1.
]

Thus, the valid range is

[
-9,223,372,036,854,775,808
]

to

[
18,446,744,073,709,551,615.
]

Values outside this range result in an error.

Although the valid range is extremely large, there is generally no practical reason to choose very large values. A simple fixed value is usually sufficient.

## **CPU and GPU Random Number Generators**

PyTorch does not necessarily use the same random-number-generation mechanism for every device.

At a conceptual level:

* **CPU:** uses a Mersenne Twister–based random-number generator.
* **CUDA GPU:** uses a Philox-based random-number generator.

The GPU generator is particularly suitable for massively parallel computation.

Therefore, the same seed does not imply that CPU and GPU will produce exactly the same numerical random sequence.

## **Does a Seed Guarantee Complete Reproducibility?**

**No.**

Setting a seed improves reproducibility, but it does not guarantee identical results in every situation.

Results may still vary because of factors such as:

* Nondeterministic GPU operations
* Different hardware
* Different PyTorch versions
* Different software environments
* Other sources of randomness such as NumPy or Python's random module
* Differences in the order in which random operations are performed

Thus, a seed should be understood as a mechanism for **controlling the starting state of pseudo-randomness**, rather than as an absolute guarantee that every experiment will always produce identical results.

## **Key Idea**

> **A seed is not the random number itself. It is used to initialize the internal state of a pseudo-random number generator. Starting the generator from the same state causes it to follow the same deterministic sequence of random-looking values, provided the relevant conditions and sequence of operations remain the same.**

The simplest mental model is:

**Seed → Initial RNG State → Deterministic PRNG Algorithm → Random-looking Sequence**

For neural networks, this allows random processes such as weight initialization and data shuffling to be controlled, making experiments easier to reproduce and compare.

.

.

## **There are several other ways to create a tensor**

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])




## **Tensor Shapes**

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[      836885349,               0,               0],
        [             97, 138160998694192, 138160998694192]])

## Difference between `torch.empty()` and `torch.empty_like()`

Both `torch.empty()` and `torch.empty_like()` are used to create tensors without initializing their memory, meaning they will contain arbitrary, uninitialized data (often referred to as 'garbage values'). However, they differ in how they determine the shape and data type of the new tensor.

*   **`torch.empty(size, *, dtype=None, device=None, requires_grad=False, pin_memory=False, memory_format=torch.contiguous_format)`**:
    *   Requires you to explicitly specify the `size` (shape) of the tensor as a tuple.
    *   You can optionally specify the `dtype`, `device`, etc. If not specified, it defaults to `torch.float32` and the current CPU device.
    *   It creates a brand new tensor with the specified shape and properties.

*   **`torch.empty_like(input, *, dtype=None, device=None, requires_grad=None, memory_format=torch.preserve_format)`**:
    *   Requires an existing `input` tensor. The new tensor will have the **same shape and data type** as the `input` tensor by default.
    *   You can *override* the `dtype` or `device` if needed, but the shape will always be inherited from the `input` tensor.
    *   It's a convenient way to create a new uninitialized tensor that mirrors the structure of an existing one.

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

## Difference between `torch.zeros()` and `torch.zeros_like()`

Both `torch.zeros()` and `torch.zeros_like()` are used to create tensors filled with zeros. Their primary difference lies in how they determine the shape and data type of the new tensor, mirroring the behavior of `torch.empty()` and `torch.empty_like()`.

*   **`torch.zeros(size, *, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)`**:
    *   Requires you to explicitly specify the `size` (shape) of the tensor as a tuple.
    *   You can optionally specify the `dtype`, `device`, etc. If not specified, it defaults to `torch.float32` and the current CPU device.
    *   It creates a brand new tensor with the specified shape and properties, with all elements initialized to zero.

*   **`torch.zeros_like(input, *, dtype=None, layout=None, device=None, requires_grad=None, memory_format=torch.preserve_format)`**:
    *   Requires an existing `input` tensor. The new tensor will have the **same shape and data type** as the `input` tensor by default.
    *   You can *override* the `dtype` or `device` if needed, but the shape will always be inherited from the `input` tensor.
    *   It's a convenient way to create a new tensor, filled with zeros, that mirrors the structure of an existing one.

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

## Difference between `torch.ones()` and `torch.ones_like()`

Both `torch.ones()` and `torch.ones_like()` are used to create tensors filled with the scalar value `1`.

*   **`torch.ones(size, ...)`**:
    *   Requires a specific **shape** (size) as an argument (e.g., `(2, 3)`).
    *   It creates a new tensor from scratch with that specific shape.
    *   Defaults to `torch.float32` unless specified otherwise.

*   **`torch.ones_like(input, ...)`**:
    *   Requires an **existing tensor** as an argument.
    *   It creates a new tensor filled with ones that has the **exact same shape and data type** as the input tensor.
    *   This is useful when you want a mask or a constant tensor that matches another tensor's dimensions without manually typing out the shape.

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Difference between `torch.rand()` and `torch.rand_like()`

*   **`torch.rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)`**: Creates a tensor with the given **shape** populated with random numbers from a uniform distribution on the interval $[0, 1)$.
*   **`torch.rand_like(input, ...)`**: Creates a tensor with the **same shape and properties** (like device and data type) as the provided `input` tensor, populated with random numbers.

### Why mention `dtype` in `torch.rand_like()`?

By default, `torch.rand_like` tries to match the `dtype` of the source tensor. However, random values (between 0 and 1) require a **floating-point** type (like `float32`).

If your source tensor `x` is an **integer tensor** (like `int64`), calling `torch.rand_like(x)` would normally result in an error because PyTorch cannot put random decimals into an integer-only tensor.

In your previous cell, you used:
`torch.rand_like(x, dtype=torch.float32)`

This tells PyTorch: "Use the **shape** of `x`, but **override** the data type to `float32` so I can store random values."

## Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.9594, 0.1334],
        [0.8591, 0.6639]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.9205, 0.0178],
        [0.7380, 0.4408]])

### 2. Element wise operation




In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0554, 0.7498, 0.3761],
        [0.6721, 0.5572, 0.2686]])
tensor([[0.3466, 0.1875, 0.7433],
        [0.6713, 0.9844, 0.0096]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0554, 0.1872, 0.3761],
        [0.0008, 0.5572, 0.0091]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 2., 9.],
        [7., 6., 5.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([18, 13])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 4., 7.])

In [ ]:
# median
torch.median(e)

tensor(5.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [ ]:
# product
torch.prod(e)

tensor(3780.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.0332)

In [ ]:
# variance
torch.var(e)

tensor(9.2000)

In [ ]:
# argmax
torch.argmax(e)

tensor(2)

In [ ]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 7, 8],
        [7, 9, 9]])
tensor([[1, 1],
        [4, 2],
        [4, 7]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[63, 73],
        [79, 88]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 7],
        [7, 9],
        [8, 9]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 2., 2.],
        [4., 8., 8.],
        [5., 0., 4.]])

In [ ]:
# determinant
torch.det(h)

tensor(224.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.1429, -0.0357,  0.0000],
        [ 0.1071,  0.0982, -0.2500],
        [-0.1786,  0.0446,  0.2500]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 1],
        [1, 1, 3]])
tensor([[2, 6, 3],
        [5, 2, 5]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 6., 4.],
        [4., 8., 6.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094, 1.3863, 0.0000],
        [1.9459, 0.0000, 2.0794]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 5.4598e+01, 2.7183e+00],
        [1.0966e+03, 2.7183e+00, 2.9810e+03]])

In [ ]:
# sqrt
torch.sqrt(k)

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.7311],
        [0.9991, 0.7311, 0.9997]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0180, 0.1192, 0.1192],
        [0.9820, 0.8808, 0.8808]])

In [ ]:
# relu
torch.relu(k)

tensor([[0., 6., 4.],
        [4., 8., 6.]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2018, 0.1089, 0.7653],
        [0.6473, 0.3401, 0.6406]])
tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])


In [ ]:
m.add_(n)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
n

tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])

In [ ]:
torch.relu(m)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m.relu_()

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

## Copying a Tensor

Let's see some examples:

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)

134838567488544

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.9985,  0.6783],
        [ 0.2776,  0.6227,  0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)

134838569581552